# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
       - '.github/workflows/swiftlint.yml'
       - '.swiftlint.yml'
       - '**/*.swift'

jobs:
  SwiftLint:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: GitHub Action for SwiftLint
       uses: norio-nomura/action-swiftlint@master
  unit_tests:
      runs-on: macos-latest
      steps:
       - name: Repository checkout
         uses: actions/checkout@v2
       - name: Select Xcode
         run: sudo xcode-select -switch /Applications/Xcode_12.app
       - name: Install Cocoapods
         run: gem install cocoapods
       - name: Build
         run:  xcodebuild clean build -workspace "TestAuth.xcworkspace" -scheme "TestAuth" -destination "platform=iOS Simulator,name=iPhone 8,OS=14.0" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
#        - name: Unit Test 
#          run:  xcodebuild test -workspace "TestAuth.xcworkspace" -scheme "GithuActionDemo" -destination "platform=iOS Simulator,name=iPhone 8,OS=14.0"

